coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

comment:
  layout: "diff, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches:
    - "main"
  hide_project_coverage: false
  show_carryforward_flags: false
  after_n_builds: 1

github_checks:
  annotations: false

ui:
  hide_sunburst: true
  hide_search: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
