coverage:
  status:
    project:
      default:
        enabled: true
        informational: true
    patch:
      default:
        enabled: true
        target: 100%
        threshold: 0
        informational: true

comment:
  layout: "newheader, diff, files, tree, newfooter"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_comment_details: true
  after_n_builds: 3
