coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

comment:
  layout: "diff, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches:
    - "main"
  hide_project_coverage: false
  show_carryforward_flags: false
  hide_comment_details: false

github_checks:
  annotations: true

ui:
  hide_sunburst: true
  hide_search: true
