name: Issue Comment Workflow
on:
  issue_comment:
    types: [created, edited]

jobs:
  proposal-police-workflow:
    runs-on: ubuntu-latest
    if: "!contains(fromJSON('[''OSBotify'', ''imgbot[bot]'', ''melvin-bot[bot]'']'), github.actor)"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: .github/scripts

      # Checks if the comment is created and follows the template OR
      # if the comment is edited and if proposal template is followed.
      # Action type logic can be found in the script files.
      - name: Run ProposalPolice™ Comment Check Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ASSISTANT_ID: ${{ secrets.OPENAI_ASSISTANT_ID }}
        run: node .github/scripts/proposalPoliceComment.js
